#CRIAÇÃO TABELA CLIENTE
CREATE TABLE TBCLIENTE(
ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
SEXO ENUM ('M', 'F'),
CPF VARCHAR(14) ,
TELEFONE VARCHAR (12) NOT NULL,
ENDERECO VARCHAR (100) NOT NULL,
BAIRRO VARCHAR (50) NOT NULL,
CIDADE VARCHAR (50) NOT NULL,
ESTADO VARCHAR (50) NOT NULL,
CEP VARCHAR (10) NOT NULL,
PRIMARY KEY (ID_CLIENTE)
)DEFAULT CHARSET = UTF8;

#INSERCAO DE DADOS NA TABELA CLIENTE
INSERT INTO TBCLIENTE
(ID_CLIENTE,NOME,SEXO,CPF,TELEFONE,ENDERECO,BAIRRO,CIDADE,ESTADO,CEP)
VALUES
('1','Leonardo Bezerra da Silva','M','763.453.236-32','3116591-3938','Quinze de Novembro 638','São Cristóvão','Itapipoca','Ceará','69986-319'),
('2','Gustavo Andrade Cruz','M','663.621.434-18','2112412-3154','Paraíba 9458','São Cristóvão','Manaus','Amazonas','99873-131'),
('3','Euder Nogueira Arcanjo','M','198.811.773-91','5965445-2552','Santa Catarina 721','Santo Antônio','Divinópolis','Minas Gerais','72852-730'),
('4','Lucas Barbaresco','M','521.385.773-68','1784893-0945','das Flores 7287','Boa Vista','Cabo de Santo Agostinho','Pernambuco','79950-411'),
('5','Matheus Vinicius do Santos Matos','M','557.662.344-49','1237449-3876','Vinte e Um 3219','Bela Vista','Boa Vista','Roraima','70507-297');

SELECT * FROM tbcliente;

#CRIAÇÃO TABELA FUNCIONARIO
CREATE TABLE TBFUNCIONARIO(

ID_FUNCIONARIO INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
SEXO ENUM ('M', 'F'),
USUARIO VARCHAR(50) NOT NULL,
SENHA VARCHAR(50) NOT NULL,
CARGO VARCHAR(30) NOT NULL,
ADMISSAO DATE NOT NULL,
TELEFONE VARCHAR(12) NOT NULL,
ENDERECO VARCHAR (100) NOT NULL,
BAIRRO VARCHAR (50) NOT NULL,
CIDADE VARCHAR (50) NOT NULL,
ESTADO VARCHAR (50) NOT NULL,
CEP VARCHAR (10) NOT NULL,
PRIMARY KEY (ID_FUNCIONARIO)

)DEFAULT CHARSET = UTF8;

#INSERCAO DE DADOS NA TABELA FUNCIONARIOS
INSERT INTO TBFUNCIONARIO
(ID_FUNCIONARIO,NOME,SEXO,USUARIO,SENHA,CARGO,ADMISSAO,TELEFONE,ENDERECO,BAIRRO,CIDADE,ESTADO,CEP)
VALUES
('1','Administrador','M','admin2021','admin2021','Administrador','2020-03-02','6543291-7481','Dezoito 867','São Francisco','Campo Grande','Mato Grosso do Sul','59376-590'),
('2','Giovanna Fialdini','F','sgngi01','nutri2021','Nutriconista','2020-03-02','8957319-5608','Sete de Setembro 4449','Planalto','Itanhaém','São Paulo','77520-292');

SELECT * FROM tbfuncionario;

#CRIAÇÃO TABELA PRODUTOS
CREATE TABLE TBPRODUTO(

ID_PRODUTO INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL UNIQUE,
DESCRICAO VARCHAR (100),
PRECO FLOAT NOT NULL,
QUANTIDADE INT,
VALIDADE DATE NOT NULL,
PRIMARY KEY (ID_PRODUTO)

)DEFAULT CHARSET = UTF8;

#INSERCAO DE DADOS NA TABELA PRODUTOS
INSERT INTO TBPRODUTO(
ID_PRODUTO, NOME, DESCRICAO, PRECO, QUANTIDADE, VALIDADE)
VALUES
('5','Marmita Carne vermelha','Arroz integral, cenoura, brócolis e filé mignon', 18.00, 50, '2021-12-17');

SELECT * FROM tbproduto;


#CRIAÇÃO TABELA PEDIDO
CREATE TABLE TBPEDIDO(
ID_PEDIDO INT NOT NULL AUTO_INCREMENT,
ID_FUNCIONARIO INT NOT NULL,
ID_CLIENTE INT NOT NULL ,
ID_PRODUTO INT NOT NULL,
QUANTIDADE INT NOT NULL,
DATA_COMPRA DATE NOT NULL,
VALOR_FINAL FLOAT, 
FORMA_PAGAMENTO VARCHAR(8),
STATUS VARCHAR(8),
PRIMARY KEY (ID_PEDIDO));

#INSERCAO DE DADOS NA TABELA PEDIDO
INSERT INTO TBPEDIDO(ID_PEDIDO, ID_FUNCIONARIO, ID_CLIENTE, ID_PRODUTO, QUANTIDADE, DATA_COMPRA, VALOR_FINAL, FORMA_PAGAMENTO, STATUS)
VALUES('1','2','1','1',10,'2021-05-11',160,'DEBITO','PAGO'),
('2','2','4','1',5,'2021-08-11',80,'DINHEIRO','PAGO'),
('3','2','2','2',6,'2021-07-11',132,'CREDITO','PENDENTE'),
('4','2','1','4',8,'2021-06-11',144,'DEBITO','PAGO'),
('5','2','3','1',12,'2021-11-11',140,'CREDITO','PENDENTE'),
('6','2','4','4',14,'2021-12-11',252,'DEBITO','RECUSADO');

SELECT * FROM TBPEDIDO;

#CRIAÇÃO TABELA COTACAO
CREATE TABLE TBCOTACAO(
ID_COTACAO INT NOT NULL AUTO_INCREMENT,
ID_PEDIDO_COMPRA INT NOT NULL,
VALOR FLOAT,
STATUS VARCHAR(8),
PRIMARY KEY (ID_COTACAO));

#INSERCAO DE DADOS NA TABELA COTACAO
INSERT INTO TBCOTACAO(ID_COTACAO,ID_PEDIDO_COMPRA,VALOR,STATUS)
VALUES('2','2',2000,'RECUSADO'),
('3','3',4000,'PENDENTE'),
('4','4',5000,'PAGO');

SELECT * FROM TBCOTACAO;

#CRIAÇÃO TABELA PEDIDO COMPRA
CREATE TABLE TBPEDIDOCOMPRA(
ID_PEDIDO_COMPRA INT NOT NULL AUTO_INCREMENT,
DESCRICAO VARCHAR(500) NOT NULL,
VALOR FLOAT NOT NULL,
PRIMARY KEY (ID_PEDIDO_COMPRA)
);


#INSERCAO DE DADOS NA PEDIDO COMPRA
INSERT INTO TBPEDIDOCOMPRA(ID_PEDIDO_COMPRA, DESCRICAO ) 
VALUES ('2', '10 saco de arroz, 15kg de carne soja , 200 gramas de legumes'),
  ('3', '5 saco de arroz, 20kg de carne vermelha, 800 gramas de legumes'),
   ('4', '30 saco de arroz, 20kg de peixe, 2kg gramas de legumes');

SELECT * FROM TBPEDIDOCOMPRA;
